[workspace]
resolver = "1"

[package]
name = "cloud"
version = "0.1.0"
edition = "2021"

[features]
default = []
plugin-contactlist = []

[dependencies]
axum = { workspace = true, features = ["ws"] }
tokio = { workspace = true, features = ["full"] }
sea-orm = { workspace = true, features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
clap = { workspace = true, features = ["derive"] }
tower-http = { workspace = true, features = ["cors", "trace"] }
dotenvy = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
futures-util = { workspace = true }
sea-orm-migration = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
base64 = { workspace = true }
sha2 = { workspace = true }
tower = { workspace = true }
axum-extra = { workspace = true, features = ["typed-header"] }
chrono = { workspace = true }
getrandom = "0.4.1"
hex = "0.4.3"
minijinja = { version = "2.15.1", features = ["loader"] }

[workspace.package]
version = "0.0.1"
authors = ["Martin Miksanik"]
description = "Cloud system"
documentation = "https://gitlab.com/xmiksay/cloud#"

[workspace.dependencies]
axum = { version = "0.7" }
tokio = { version = "1.0" }
sea-orm = { version = "1.0" }
serde = { version = "1.0" }
serde_json = "1.0"
clap = { version = "4.0" }
tower-http = { version = "0.5", features = ["fs", "cors"] }
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3" }
futures-util = "0.3"
sea-orm-migration = { version = "1.0", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
uuid = { version = "1.1" }
base64 = "0.22"
sha2 = "0.10"
tower = "0.4"
axum-extra = "0.9"
chrono = "0.4"
