[workspace]
resolver = "2"
members = ["backend", "launcher", "web", "plugins/audio", "plugins/video", "plugins/image", "plugins/git"]

[workspace.package]
version = "0"
authors = "Martin Miksanik"
description = "Cloud system"
documentation = "https://gitlab.com/xmiksay/cloud#"

[workspace.dependencies]
