/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all groups
         *     GET /api/group
         */
        get: operations["list_groups_handler"];
        put?: never;
        /**
         * Create new group
         *     POST /api/group
         */
        post: operations["create_group_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get group by ID
         *     GET /api/group/:id
         */
        get: operations["get_group_handler"];
        /**
         * Update group
         *     PUT /api/group/:id
         */
        put: operations["update_group_handler"];
        post?: never;
        /**
         * Delete group
         *     DELETE /api/group/:id
         */
        delete: operations["delete_group_handler"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint (no auth required) */
        get: operations["health_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all photos without a date
         *     GET /api/photo
         */
        get: operations["list_photos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photo/list/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List photos by year
         *     GET /api/photo/list/:year
         */
        get: operations["list_by_year"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photo/list/{year}/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List photos by year and month
         *     GET /api/photo/list/:year/:month
         */
        get: operations["list_by_year_month"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photo/list/{year}/{month}/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List photos by year, month, and day
         *     GET /api/photo/list/:year/:month/:day
         */
        get: operations["list_by_year_month_day"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photo/regenerate/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate thumbnail for a photo
         *     POST /api/photo/regenerate/:hash
         */
        post: operations["regenerate_thumbnail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List storages the caller can access (owner, group member, share recipient,
         *     or admin — mirrors `require_storage_access`) endpoint
         *     GET /api/storage
         */
        get: operations["list_storages_handler"];
        put?: never;
        /**
         * Create new storage
         *     POST /api/storage
         */
        post: operations["create_storage_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/meta/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get meta information by hash
         *     GET /api/storage/meta/:hash
         */
        get: operations["get_meta_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all shares owned by the current user
         *     GET /api/storage/share
         */
        get: operations["list_all_user_shares_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/share/with-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List shares shared with the current user
         *     GET /api/storage/share/with-me
         */
        get: operations["list_shares_with_me_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/share/{share_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get share info
         *     GET /api/storage/share/:share_id
         */
        get: operations["get_share_info_handler"];
        /**
         * Update a share
         *     PUT /api/storage/share/:share_id
         */
        put: operations["update_share_handler"];
        post?: never;
        /**
         * Delete a share
         *     DELETE /api/storage/share/:share_id
         */
        delete: operations["delete_share_handler"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/share/{share_id}/create/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create file or folder via share
         *     POST /api/storage/share/:share_id/create/*path
         */
        post: operations["share_create_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/share/{share_id}/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List share root directory
         *     GET /api/storage/share/:share_id/list
         */
        get: operations["share_list_root_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/share/{share_id}/list/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List share subdirectory
         *     GET /api/storage/share/:share_id/list/*path
         */
        get: operations["share_list_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/share/{share_id}/remove/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete file or folder via share
         *     DELETE /api/storage/share/:share_id/remove/*path
         */
        delete: operations["share_remove_handler"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/share/{share_id}/rename/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rename file or folder via share
         *     POST /api/storage/share/:share_id/rename/*path
         */
        post: operations["share_rename_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/share/{share_id}/show/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get file content via share
         *     GET /api/storage/share/:share_id/show/*path
         */
        get: operations["share_show_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/share/{share_id}/tags/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the tags on a file or directory via share
         *     PUT /api/storage/share/:share_id/tags/*path
         */
        put: operations["share_update_entry_tags_handler"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/share/{share_id}/update/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update file content via share
         *     PUT /api/storage/share/:share_id/update/*path
         */
        put: operations["share_update_handler"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/thumbnail/{hash}/{size}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Thumbnail endpoint - serves thumbnail by entry hash (requires access to a
         *     storage entry with this content hash, same gate as `get_meta_handler`)
         *     GET /api/storage/thumbnail/:hash/:size
         */
        get: operations["thumbnail_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get storage by ID
         *     GET /api/storage/:id
         */
        get: operations["get_storage_handler"];
        /**
         * Update storage
         *     PUT /api/storage/:id
         */
        put: operations["update_storage_handler"];
        post?: never;
        /**
         * Delete storage
         *     DELETE /api/storage/:id
         */
        delete: operations["delete_storage_handler"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/{id}/create/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new file or directory entry
         *     POST /api/storage/:id/create/*path
         */
        post: operations["create_entry_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/{id}/hash/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger file processing job
         *     POST /api/storage/:id/hash/*path?mode=auto|force|hash_only
         */
        post: operations["trigger_hash_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/{id}/list/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List directory contents (JSON)
         *     GET /api/storage/:id/list/*path
         */
        get: operations["list_directory_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/{id}/raw/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download file as octet-stream
         *     GET /api/storage/:id/raw/*path
         */
        get: operations["download_file_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/{id}/remove/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a file or directory
         *     DELETE /api/storage/:id/remove/*path
         */
        delete: operations["remove_entry_handler"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/{id}/rename/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rename a file or directory
         *     POST /api/storage/:id/rename/*path
         */
        post: operations["rename_entry_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/{id}/share/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List shares for an entry
         *     GET /api/storage/:id/share/*path
         */
        get: operations["list_shares_handler"];
        put?: never;
        /**
         * Create a share for an entry
         *     POST /api/storage/:id/share/*path
         */
        post: operations["share_entry_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/{id}/show/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get file content with detected content type
         *     GET /api/storage/:id/show/*path
         */
        get: operations["get_file_content_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/{id}/tags/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the tags on a file or directory
         *     PUT /api/storage/:id/tags/*path
         */
        put: operations["update_entry_tags_handler"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/{id}/update/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update file content
         *     PUT /api/storage/:id/update/*path
         */
        put: operations["update_file_content_handler"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all tags for the current user
         *     GET /api/tag
         */
        get: operations["list_tags_handler"];
        put?: never;
        /**
         * Create new tag
         *     POST /api/tag
         */
        post: operations["create_tag_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tag/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tag by ID (only if it belongs to the user)
         *     GET /api/tag/:id
         */
        get: operations["get_tag_handler"];
        /**
         * Update tag
         *     PUT /api/tag/:id
         */
        put: operations["update_tag_handler"];
        post?: never;
        /**
         * Delete tag
         *     DELETE /api/tag/:id
         */
        delete: operations["delete_tag_handler"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all users
         *     GET /api/user
         */
        get: operations["list_users_handler"];
        put?: never;
        /**
         * Create new user
         *     POST /api/user
         */
        post: operations["create_user_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login endpoint - accepts JSON payload with username/password
         *     POST /api/user/login
         */
        post: operations["login_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout endpoint - revokes the current session token and clears the cookie
         *     POST /api/user/logout
         */
        post: operations["logout_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me endpoint - returns current user info
         *     GET /api/user/me
         */
        get: operations["me_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user by ID
         *     GET /api/user/:id
         */
        get: operations["get_user_handler"];
        /**
         * Update user
         *     PUT /api/user/:id
         */
        put: operations["update_user_handler"];
        post?: never;
        /**
         * Delete user
         *     DELETE /api/user/:id
         */
        delete: operations["delete_user_handler"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change password handler
         *     POST /api/user/:id/password
         */
        post: operations["change_password_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version endpoint */
        get: operations["version_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Change password request */
        ChangePasswordRequest: {
            password: string;
        };
        /** @description Create entry request */
        CreateEntryRequest: {
            entry_type: components["schemas"]["EntryType"];
            notify?: boolean;
        };
        /** @description Create group request */
        CreateGroupRequest: {
            description?: string | null;
            name: string;
        };
        /** @description Create storage request */
        CreateStorageRequest: {
            /** Format: int32 */
            default_group: number;
            /** Format: int32 */
            default_user: number;
            description?: string | null;
            ignore_patterns?: string | null;
            name: string;
            path: string;
        };
        /** @description Create tag request */
        CreateTagRequest: {
            description?: string | null;
            name: string;
        };
        /** @description Create user request */
        CreateUserRequest: {
            admin?: boolean | null;
            description?: string | null;
            enabled?: boolean | null;
            name: string;
            password: string;
            username: string;
        };
        DirectoryEntry: {
            /** Format: date-time */
            created_at: string;
            entry_type: components["schemas"]["EntryType"];
            /** Format: int32 */
            group_id: number;
            hash?: number[] | null;
            /** Format: int32 */
            id?: number | null;
            /** Format: date-time */
            modified_at: string;
            notify: boolean;
            /** Format: int32 */
            parent_id?: number | null;
            path: string;
            /** Format: int64 */
            size: number;
            /** Format: int32 */
            storage_id: number;
            /** Format: int32 */
            user_id: number;
        };
        /** @description Directory listing response: the entries under a storage path. */
        DirectoryListingResponse: {
            entries: components["schemas"]["DirectoryEntry"][];
            /** @description Normalized (slash-trimmed) directory path within the storage. */
            path: string;
            /** Format: int32 */
            storage_id: number;
        };
        /**
         * @description Entry type enum - File, Directory, or Symlink
         * @enum {string}
         */
        EntryType: "File" | "Directory" | "Symlink";
        /** @description Error response */
        ErrorResponse: {
            error: string;
        };
        /** @description Group response */
        GroupResponse: {
            description?: string | null;
            /** Format: int32 */
            id: number;
            name: string;
        };
        /** @description Health check response. */
        HealthResponse: {
            /** @description Database connectivity: `ok` or `error`. */
            database: string;
            /** @description Service identifier. */
            service: string;
            /** @description Overall service status (always `ok` if the process is serving). */
            status: string;
        };
        /** @description Login request payload */
        LoginRequest: {
            password: string;
            username: string;
        };
        /**
         * @description Login response
         *
         *     The session token itself is never returned in the body (issue #10) — it's
         *     only ever carried in the HttpOnly `session_token` cookie set alongside
         *     this response, so it stays out of reach of any XSS-injected JavaScript.
         */
        LoginResponse: {
            /** Format: int64 */
            expires_in_days: number;
        };
        /** @description Current-user summary returned by `GET /api/user/me`. */
        MeResponse: {
            admin: boolean;
            /** Format: int32 */
            id: number;
            name: string;
            username: string;
        };
        /**
         * @description A generic `{ "message": "..." }` acknowledgement body.
         *
         *     The single envelope for endpoints whose only useful response is a
         *     human-readable confirmation (deletes, queued jobs, tag updates, …).
         *     Replaces the scattered ad-hoc `Json(json!({ "message": ... }))` so every
         *     such endpoint shares one typed, OpenAPI-documented shape.
         */
        MessageResponse: {
            message: string;
        };
        /** @description Meta response */
        MetaResponse: {
            custom: unknown;
            hash: string;
            keywords: string[];
            tags: number[];
        };
        /**
         * @description A single page of results plus the metadata a client needs to walk the rest.
         *     The uniform envelope returned by every paginated list endpoint.
         */
        Page_GroupResponse: {
            /** @description Items in this page. */
            items: {
                description?: string | null;
                /** Format: int32 */
                id: number;
                name: string;
            }[];
            /**
             * Format: int64
             * @description 1-based page number this response represents.
             */
            page: number;
            /**
             * Format: int64
             * @description Page size used to build this response.
             */
            per_page: number;
            /**
             * Format: int64
             * @description Total number of items across all pages.
             */
            total: number;
            /**
             * Format: int64
             * @description Total number of pages at this `per_page` (at least 1).
             */
            total_pages: number;
        };
        /**
         * @description A single page of results plus the metadata a client needs to walk the rest.
         *     The uniform envelope returned by every paginated list endpoint.
         */
        Page_StorageResponse: {
            /** @description Items in this page. */
            items: {
                /** Format: int32 */
                default_group: number;
                /** Format: int32 */
                default_user: number;
                description?: string | null;
                /** Format: int32 */
                id: number;
                ignore_patterns: string;
                name: string;
                path: string;
            }[];
            /**
             * Format: int64
             * @description 1-based page number this response represents.
             */
            page: number;
            /**
             * Format: int64
             * @description Page size used to build this response.
             */
            per_page: number;
            /**
             * Format: int64
             * @description Total number of items across all pages.
             */
            total: number;
            /**
             * Format: int64
             * @description Total number of pages at this `per_page` (at least 1).
             */
            total_pages: number;
        };
        /**
         * @description A single page of results plus the metadata a client needs to walk the rest.
         *     The uniform envelope returned by every paginated list endpoint.
         */
        Page_TagResponse: {
            /** @description Items in this page. */
            items: {
                description?: string | null;
                /** Format: int32 */
                id: number;
                name: string;
            }[];
            /**
             * Format: int64
             * @description 1-based page number this response represents.
             */
            page: number;
            /**
             * Format: int64
             * @description Page size used to build this response.
             */
            per_page: number;
            /**
             * Format: int64
             * @description Total number of items across all pages.
             */
            total: number;
            /**
             * Format: int64
             * @description Total number of pages at this `per_page` (at least 1).
             */
            total_pages: number;
        };
        /**
         * @description A single page of results plus the metadata a client needs to walk the rest.
         *     The uniform envelope returned by every paginated list endpoint.
         */
        Page_UserResponse: {
            /** @description Items in this page. */
            items: {
                admin: boolean;
                description?: string | null;
                enabled: boolean;
                /** Format: int32 */
                id: number;
                name: string;
                username: string;
            }[];
            /**
             * Format: int64
             * @description 1-based page number this response represents.
             */
            page: number;
            /**
             * Format: int64
             * @description Page size used to build this response.
             */
            per_page: number;
            /**
             * Format: int64
             * @description Total number of items across all pages.
             */
            total: number;
            /**
             * Format: int64
             * @description Total number of pages at this `per_page` (at least 1).
             */
            total_pages: number;
        };
        PhotoResponse: {
            date?: string | null;
            hash: string;
            keywords: string[];
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
            path?: string | null;
            /** Format: int32 */
            storage_id?: number | null;
        };
        /** @description Rename entry request */
        RenameEntryRequest: {
            new_path: string;
        };
        /**
         * @description Share entry request
         *
         *     The same body is used for create (`POST`) and update (`PUT`); both apply
         *     the fields with replace semantics — the request fully describes the share.
         */
        ShareEntryRequest: {
            can_write: boolean;
            /**
             * Format: int64
             * @description Days until the share expires, counted from now.
             *
             *     One expiry contract shared by create and update (issue #9 / B8): a
             *     positive value sets `expires_at = now + days`; `0`, `null`, or an
             *     absent field means the share never expires. Create and update treat
             *     this value identically.
             */
            expires_in_days?: number | null;
            group_ids: number[];
            public_link: boolean;
            user_ids: number[];
        };
        /** @description Public metadata about a single share (no secret token is ever included). */
        ShareInfoResponse: {
            can_write: boolean;
            /** @description `File` or `Directory`. */
            entry_type: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: int32 */
            id: number;
            /** @description Basename of the shared entry. */
            name: string;
            path: string;
            /** Format: int32 */
            storage_id: number;
        };
        /**
         * @description Share response
         *
         *     `shared.token` stores a hash of the public-link token (issue #10), not the
         *     plaintext, so it can no longer be read back from the database. `token` is
         *     therefore only ever populated with the plaintext immediately after it is
         *     generated (on creation, or on regeneration via update) — callers must
         *     capture it then, as it cannot be recovered later. `has_public_link`
         *     reflects whether a public link exists at all, independent of whether the
         *     plaintext is known in this response.
         */
        ShareResponse: {
            can_write: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at?: string | null;
            group_ids: number[];
            has_public_link: boolean;
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            owner_id: number;
            path: string;
            /** Format: int32 */
            storage_id: number;
            token?: string | null;
            user_ids: number[];
        };
        /** @description Storage response */
        StorageResponse: {
            /** Format: int32 */
            default_group: number;
            /** Format: int32 */
            default_user: number;
            description?: string | null;
            /** Format: int32 */
            id: number;
            ignore_patterns: string;
            name: string;
            path: string;
        };
        /** @description Tag response */
        TagResponse: {
            description?: string | null;
            /** Format: int32 */
            id: number;
            name: string;
        };
        /** @description Update entry tags request */
        UpdateEntryTagsRequest: {
            tags: number[];
        };
        /** @description Update group request */
        UpdateGroupRequest: {
            description?: string | null;
            name?: string | null;
        };
        /** @description Update storage request (all fields optional) */
        UpdateStorageRequest: {
            /** Format: int32 */
            default_group?: number | null;
            /** Format: int32 */
            default_user?: number | null;
            description?: string | null;
            ignore_patterns?: string | null;
            name?: string | null;
            path?: string | null;
        };
        /** @description Update tag request */
        UpdateTagRequest: {
            description?: string | null;
            name?: string | null;
        };
        /** @description Update user request */
        UpdateUserRequest: {
            admin?: boolean | null;
            description?: string | null;
            enabled?: boolean | null;
            name?: string | null;
            password?: string | null;
            username?: string | null;
        };
        /** @description User response (without password) */
        UserResponse: {
            admin: boolean;
            description?: string | null;
            enabled: boolean;
            /** Format: int32 */
            id: number;
            name: string;
            username: string;
        };
        /** @description Build/version response. */
        VersionResponse: {
            /** @description Embedded git commit hash of the running binary. */
            commit: string;
            /** @description Cargo package version. */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_groups_handler: {
        parameters: {
            query?: {
                /** @description 1-based page number (default 1). */
                page?: number;
                /** @description Items per page (default 50, capped at 200). */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_GroupResponse"];
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_group_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Group created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Group already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_group_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_group_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupRequest"];
            };
        };
        responses: {
            /** @description Group updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Group name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_group_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Cannot delete group with users */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_photos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of photos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoResponse"][];
                };
            };
        };
    };
    list_by_year: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Year */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of photos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoResponse"][];
                };
            };
            /** @description Invalid year */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_by_year_month: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Year */
                year: number;
                /** @description Month */
                month: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of photos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoResponse"][];
                };
            };
            /** @description Invalid year/month */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_by_year_month_day: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Year */
                year: number;
                /** @description Month */
                month: number;
                /** @description Day */
                day: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of photos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoResponse"][];
                };
            };
            /** @description Invalid date */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    regenerate_thumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Photo hash */
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Regeneration queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Photo not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_storages_handler: {
        parameters: {
            query?: {
                /** @description 1-based page number (default 1). */
                page?: number;
                /** @description Items per page (default 50, capped at 200). */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of accessible storages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StorageResponse"];
                };
            };
        };
    };
    create_storage_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStorageRequest"];
            };
        };
        responses: {
            /** @description Storage created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageResponse"];
                };
            };
            /** @description Invalid path */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Storage already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_meta_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File content hash (hex-encoded) */
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meta information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
            /** @description Invalid hash format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Meta not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_all_user_shares_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of user's shares */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareResponse"][];
                };
            };
        };
    };
    list_shares_with_me_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of shares shared with user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareResponse"][];
                };
            };
        };
    };
    get_share_info_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share ID or token */
                share_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Share info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareInfoResponse"];
                };
            };
            /** @description Share not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_share_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share ID */
                share_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareEntryRequest"];
            };
        };
        responses: {
            /** @description Share updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareResponse"];
                };
            };
            /** @description Share not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_share_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share ID */
                share_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Share deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    share_create_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share ID or token */
                share_id: string;
                /** @description Entry path */
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntryRequest"];
            };
        };
        responses: {
            /** @description Entry created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Write access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    share_list_root_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share ID or token */
                share_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Share not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    share_list_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share ID or token */
                share_id: string;
                /** @description Subdirectory path */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Share not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    share_remove_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share ID or token */
                share_id: string;
                /** @description Entry path */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Write access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    share_rename_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share ID or token */
                share_id: string;
                /** @description Current entry path */
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameEntryRequest"];
            };
        };
        responses: {
            /** @description Entry renamed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Write access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    share_show_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share ID or token */
                share_id: string;
                /** @description File path */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    share_update_entry_tags_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share ID or token */
                share_id: string;
                /** @description Entry path */
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEntryTagsRequest"];
            };
        };
        responses: {
            /** @description Tags updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Write access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entry has not been hashed yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    share_update_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share ID or token */
                share_id: string;
                /** @description File path */
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": number[];
            };
        };
        responses: {
            /** @description File updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Write access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    thumbnail_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entry hash */
                hash: string;
                /** @description Thumbnail size (small, large, mini) */
                size: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thumbnail image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Invalid hash or size */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access denied to this content */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Thumbnail not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_storage_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Storage found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageResponse"];
                };
            };
            /** @description Access denied to this storage */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Storage not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_storage_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStorageRequest"];
            };
        };
        responses: {
            /** @description Storage updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageResponse"];
                };
            };
            /** @description Invalid path */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Storage not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Storage path/name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_storage_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Storage deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Storage not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Cannot delete storage with entries */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_entry_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage ID */
                id: number;
                /** @description Entry path */
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntryRequest"];
            };
        };
        responses: {
            /** @description Entry created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unsupported entry type */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    trigger_hash_handler: {
        parameters: {
            query?: {
                /** @description Processing mode: auto (default), force, hash_only */
                mode?: string;
            };
            header?: never;
            path: {
                /** @description Storage ID */
                id: number;
                /** @description File path */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Processing job queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_directory_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage ID */
                id: number;
                /** @description Directory path */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryListingResponse"];
                };
            };
            /** @description Storage not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    download_file_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage ID */
                id: number;
                /** @description File path */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File download */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_entry_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage ID */
                id: number;
                /** @description Entry path */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error removing entry */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rename_entry_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage ID */
                id: number;
                /** @description Current entry path */
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameEntryRequest"];
            };
        };
        responses: {
            /** @description Entry renamed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error renaming entry */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_shares_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage ID */
                id: number;
                /** @description Entry path */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of shares */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareResponse"][];
                };
            };
        };
    };
    share_entry_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage ID */
                id: number;
                /** @description Entry path */
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareEntryRequest"];
            };
        };
        responses: {
            /** @description Share created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareResponse"];
                };
            };
            /** @description Path not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_file_content_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage ID */
                id: number;
                /** @description File path */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_entry_tags_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage ID */
                id: number;
                /** @description Entry path */
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEntryTagsRequest"];
            };
        };
        responses: {
            /** @description Tags updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Entry has not been hashed yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_file_content_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Storage ID */
                id: number;
                /** @description File path */
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": number[];
            };
        };
        responses: {
            /** @description File updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Storage not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_tags_handler: {
        parameters: {
            query?: {
                /** @description 1-based page number (default 1). */
                page?: number;
                /** @description Items per page (default 50, capped at 200). */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TagResponse"];
                };
            };
        };
    };
    create_tag_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagRequest"];
            };
        };
        responses: {
            /** @description Tag created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"];
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tag already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_tag_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tag ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"];
                };
            };
            /** @description Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_tag_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tag ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTagRequest"];
            };
        };
        responses: {
            /** @description Tag updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"];
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tag name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_tag_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tag ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_users_handler: {
        parameters: {
            query?: {
                /** @description 1-based page number (default 1). */
                page?: number;
                /** @description Items per page (default 50, capped at 200). */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserResponse"];
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_user_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Username already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    get_user_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_user_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description User updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Username already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_user_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot delete own account */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    change_password_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    version_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build/version info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
