[package]
name = "byteburrow-plugin-face"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Face detection plugin for ByteBurrow"

[lib]
crate-type = ["cdylib"]

[dependencies]
byteburrow-plugin-api = { path = "../../byteburrow-plugin-api" }
rustface = "0.1"
image = { workspace = true }
serde_json = { workspace = true }
