[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { workspace = true, features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
sea-orm-migration = { workspace = true }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4", "serde"] }
dotenvy = { workspace = true }
