[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true, features = ["ws"] }
tokio = { workspace = true, features = ["full"] }
sea-orm = { workspace = true, features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
shared = { path = "../shared" }
futures-util = { workspace = true }
tower-http = { workspace = true, features = ["fs", "cors"] }
